"""
cv/anomaly_evaluate.py — Evaluate the trained anomaly autoencoder: ROC
curve, AUC, and example reconstructions.

Synthetic anomalies are generated by perturbing REAL held-out normal
images (the same ones cv.anomaly_train computed the threshold from) in
two ways the project spec calls for:
  1. "flare" — a bright, saturated synthetic glare spot, simulating lens
     flare or a sun-glint artifact.
  2. "deleted" — a rectangular region blacked out, simulating a missing/
     occluded object (e.g. a solar panel that should be visible but
     isn't, or a dropped sensor region).
This keeps the comparison paired and honest: each anomalous sample is a
real photo with one realistic, controlled defect, not an unrelated
random image — the reconstruction error increase is directly
attributable to the injected defect, which is what makes the ROC
analysis meaningful.

Run: ./.venv/bin/python -m cv.anomaly_evaluate
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # headless — this project has no GUI backend available in most run contexts
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve

from cv.anomaly import AnomalyDetector, SpaceAutoencoder, reconstruction_error
from cv.anomaly_train import HOLDOUT_FRACTION, IMAGE_DIR, META_PATH, WEIGHTS_PATH, load_and_preprocess_images

MODEL_DIR = Path(__file__).resolve().parent.parent / "models"
ROC_PLOT_PATH = MODEL_DIR / "anomaly_roc_curve.png"
EXAMPLES_PLOT_PATH = MODEL_DIR / "anomaly_examples.png"


def add_flare(image: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """Inject a bright synthetic glare/flare spot — a real, common optical defect."""
    out = image.copy()
    size = image.shape[0]
    cx, cy = rng.integers(size // 4, 3 * size // 4, size=2)
    radius = rng.integers(size // 8, size // 4)
    yy, xx = np.indices((size, size))
    dist = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)
    glare = np.clip(1.0 - dist / radius, 0, 1) ** 2
    return np.clip(out + glare, 0, 1).astype(np.float32)


def delete_region(image: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """Black out a rectangular region — simulates a missing/occluded object."""
    out = image.copy()
    size = image.shape[0]
    w, h = rng.integers(size // 5, size // 2, size=2)
    x0 = rng.integers(0, max(1, size - w))
    y0 = rng.integers(0, max(1, size - h))
    out[y0 : y0 + h, x0 : x0 + w] = 0.0
    return out


def build_evaluation_set(normal_images: np.ndarray, seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
    """
    Returns (images, labels): each real normal image contributes itself
    (label 0) plus one flare-perturbed and one deletion-perturbed variant
    (label 1 each) — a balanced, paired anomalous set.
    """
    rng = np.random.default_rng(seed)
    images, labels = [], []
    for img in normal_images:
        images.append(img)
        labels.append(0)
        images.append(add_flare(img, rng))
        labels.append(1)
        images.append(delete_region(img, rng))
        labels.append(1)
    return np.stack(images), np.array(labels)


def main() -> None:
    if not WEIGHTS_PATH.exists():
        raise RuntimeError(f"No trained model at {WEIGHTS_PATH} — run `python -m cv.anomaly_train` first.")

    detector = AnomalyDetector.load(WEIGHTS_PATH, META_PATH)
    print(f"Loaded trained model, current threshold: {detector.threshold:.5f}")

    # Re-derive the exact same holdout split cv.anomaly_train used (same
    # seed, same source images already saved to disk) so evaluation is on
    # genuinely held-out data, not images the model trained on.
    image_paths = sorted((IMAGE_DIR / "images" / "train").glob("*.jpg"))
    all_images = load_and_preprocess_images(image_paths)
    rng = np.random.default_rng(42)
    idx = rng.permutation(len(all_images))
    n_holdout = max(4, int(len(all_images) * HOLDOUT_FRACTION))
    holdout_images = all_images[idx[:n_holdout]]
    print(f"Evaluating on {len(holdout_images)} held-out real normal images + their synthetic-anomaly variants")

    eval_images, labels = build_evaluation_set(holdout_images)
    errors = reconstruction_error(detector.model, eval_images)

    auc = roc_auc_score(labels, errors)
    fpr, tpr, thresholds = roc_curve(labels, errors)
    # Youden's J statistic: the threshold that maximizes (TPR - FPR) —
    # the standard "best single operating point" pick from an ROC curve,
    # to compare against the simpler mean+2*std rule cv.anomaly_train uses.
    j_scores = tpr - fpr
    best_idx = int(np.argmax(j_scores))
    youden_threshold = float(thresholds[best_idx])

    print(f"ROC AUC: {auc:.4f}")
    print(f"Youden's-J-optimal threshold: {youden_threshold:.5f} (TPR={tpr[best_idx]:.3f}, FPR={fpr[best_idx]:.3f})")
    print(f"Trained (mean+2*std) threshold: {detector.threshold:.5f}")

    def _confusion(threshold: float) -> tuple[float, float, float, int, int, int, int]:
        predicted = errors > threshold
        tp = int(np.sum(predicted & (labels == 1)))
        fn = int(np.sum(~predicted & (labels == 1)))
        fp = int(np.sum(predicted & (labels == 0)))
        tn = int(np.sum(~predicted & (labels == 0)))
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
        return precision, recall, f1, tp, fn, fp, tn

    trained_p, trained_r, trained_f1, tp, fn, fp, tn = _confusion(detector.threshold)
    print(f"At trained (mean+2*std) threshold {detector.threshold:.5f}: precision={trained_p:.3f}, recall={trained_r:.3f}, F1={trained_f1:.3f} (TP={tp} FN={fn} FP={fp} TN={tn})")

    youden_p, youden_r, youden_f1, tp2, fn2, fp2, tn2 = _confusion(youden_threshold)
    print(f"At Youden's-J threshold {youden_threshold:.5f}: precision={youden_p:.3f}, recall={youden_r:.3f}, F1={youden_f1:.3f} (TP={tp2} FN={fn2} FP={fp2} TN={tn2})")

    # The whole point of this evaluation: don't just report a bad
    # threshold, fix it. If the naive mean+2*std rule turns out to have
    # near-zero recall against these real perturbation types (verified
    # here, not assumed) while the ROC-derived operating point does
    # meaningfully better, actually deploy the better one — this is what
    # "Optimal eşiği belirle" means in practice, not just printing a number.
    if trained_f1 < youden_f1:
        print(f"Naive threshold underperforms (F1 {trained_f1:.3f} < {youden_f1:.3f}) — updating deployed threshold to the ROC-optimal value.")
        detector.threshold = youden_threshold
        detector.save(WEIGHTS_PATH, META_PATH)
        print(f"Deployed threshold updated: {META_PATH} now has threshold={youden_threshold:.5f}")

    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.plot(fpr, tpr, label=f"ROC (AUC = {auc:.3f})", color="#00cccc")
    ax.plot([0, 1], [0, 1], "--", color="gray", label="Chance")
    ax.scatter([fpr[best_idx]], [tpr[best_idx]], color="#ff3355", zorder=5, label="Youden's J optimum")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title("Anomaly Autoencoder ROC — real NASA imagery + synthetic flare/deletion defects")
    ax.legend()
    fig.tight_layout()
    fig.savefig(ROC_PLOT_PATH, dpi=120)
    plt.close(fig)
    print(f"Saved ROC curve to {ROC_PLOT_PATH}")

    # A handful of example original/anomalous images with their scores, for visual sanity-checking.
    n_examples = min(4, len(holdout_images))
    fig, axes = plt.subplots(n_examples, 3, figsize=(7, 2.2 * n_examples))
    if n_examples == 1:
        axes = axes[np.newaxis, :]
    example_rng = np.random.default_rng(123)
    for row in range(n_examples):
        base = holdout_images[row]
        flared = add_flare(base, example_rng)
        deleted = delete_region(base, example_rng)
        for col, (img, title) in enumerate([(base, "normal"), (flared, "flare"), (deleted, "deleted region")]):
            err = float(reconstruction_error(detector.model, img[np.newaxis, ...])[0])
            flag = "ANOMALY" if err > detector.threshold else "normal"
            axes[row, col].imshow(img, cmap="gray", vmin=0, vmax=1)
            axes[row, col].set_title(f"{title}\nerr={err:.4f} [{flag}]", fontsize=8)
            axes[row, col].axis("off")
    fig.tight_layout()
    fig.savefig(EXAMPLES_PLOT_PATH, dpi=120)
    plt.close(fig)
    print(f"Saved example grid to {EXAMPLES_PLOT_PATH}")


if __name__ == "__main__":
    main()
